# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setFixedSize(500, 700)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo_icon.svg"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
                                 "    background-color: white;\n"
                                 "    font-family: Roboto;\n"
                                 "    \n"
                                 "    font-weight: 600;\n"
                                 "\n"
                                 "    \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "    background-color: #3867e8;\n"
                                 "    padding-top:5px;\n"
                                 "    padding-bottom:5px;\n"
                                 "    color:white;\n"
                                 "    font-size:16px;\n"
                                 "    font-weight: 800;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "    background-color: #1ba2d1;\n"
                                 "    \n"
                                 "}\n"
                                 "QLabel{\n"
                                 "    color:#3867e8;\n"
                                 "    font-size: 24px;\n"
                                 "}\n"
                                 "QListWidget{\n"
                                 "    background-color: #1ba2d1;\n"
                                 "    border-radius: 5px;\n"
                                 "    color:white;\n"
                                 "    font-size: 16px;\n"
                                 "\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 500, 50))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btn_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(30, 590, 200, 40))
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(150, 650, 200, 40))
        self.btn_stop.setObjectName("btn_stop")
        self.btn_faq = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_faq.setGeometry(QtCore.QRect(270, 590, 200, 40))
        self.btn_faq.setObjectName("btn_faq")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 460, 510))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "VoiceAssistantEva"))
        self.label.setText(_translate("MainWindow", "Ева"))
        self.btn_start.setText(_translate("MainWindow", "Начать"))
        self.btn_stop.setText(_translate("MainWindow", "Справка"))
        self.btn_faq.setText(_translate("MainWindow", "Стоп"))
